<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class AbsensiTableSeeder extends Seeder
{
    public function run()
    {
        DB::table('absensi')->insert([
            [
                'id' => 62,
                'data_karyawan_id' => '5-01',
                'nama' => 'A. Yusril Mahendra',
                'divisi' => 'Pengawas Lapangan',
                'jumlah_hadir' => 27,
                'mulai' => null,
                'berakhir' => null,
                'created_at' => '2024-09-10 08:10:06',
                'updated_at' => '2024-09-10 08:10:06',
            ],
            [
                'id' => 63,
                'data_karyawan_id' => '5-02',
                'nama' => 'Abd Rahman',
                'divisi' => 'Cook',
                'jumlah_hadir' => 28,
                'mulai' => null,
                'berakhir' => null,
                'created_at' => '2024-09-10 08:10:06',
                'updated_at' => '2024-09-10 08:10:06',
            ],
            [
                'id' => 64,
                'data_karyawan_id' => '5-03',
                'nama' => 'Adam Achmad Labisa',
                'divisi' => 'Cook',
                'jumlah_hadir' => 5,
                'mulai' => null,
                'berakhir' => null,
                'created_at' => '2024-09-10 08:10:06',
                'updated_at' => '2024-09-10 08:10:06',
            ],
            [
                'id' => 65,
                'data_karyawan_id' => '5-04',
                'nama' => 'Ade Ratih',
                'divisi' => 'Hall Cashier',
                'jumlah_hadir' => 24,
                'mulai' => null,
                'berakhir' => null,
                'created_at' => '2024-09-10 08:10:06',
                'updated_at' => '2024-09-10 08:10:06',
            ],
            [
                'id' => 66,
                'data_karyawan_id' => '5-05',
                'nama' => 'Ahmad Dani',
                'divisi' => 'Hall Waiters',
                'jumlah_hadir' => 13,
                'mulai' => null,
                'berakhir' => null,
                'created_at' => '2024-09-10 08:10:06',
                'updated_at' => '2024-09-10 08:10:06',
            ],
            [
                'id' => 67,
                'data_karyawan_id' => '5-06',
                'nama' => 'Ahmad Sodiqin',
                'divisi' => 'Hall Cleaning Service',
                'jumlah_hadir' => 9,
                'mulai' => null,
                'berakhir' => null,
                'created_at' => '2024-09-10 08:10:06',
                'updated_at' => '2024-09-10 08:10:06',
            ],
            [
                'id' => 68,
                'data_karyawan_id' => '5-07',
                'nama' => 'Akmal',
                'divisi' => 'Pembakaran',
                'jumlah_hadir' => 28,
                'mulai' => null,
                'berakhir' => null,
                'created_at' => '2024-09-10 08:10:06',
                'updated_at' => '2024-09-10 08:10:06',
            ],
            [
                'id' => 69,
                'data_karyawan_id' => '5-08',
                'nama' => 'Ali Akbar',
                'divisi' => 'Bar',
                'jumlah_hadir' => 27,
                'mulai' => null,
                'berakhir' => null,
                'created_at' => '2024-09-10 08:10:06',
                'updated_at' => '2024-09-10 08:10:06',
            ],
            [
                'id' => 70,
                'data_karyawan_id' => '5-09',
                'nama' => 'Andi Rivaldi',
                'divisi' => 'Hall Cleaning Service',
                'jumlah_hadir' => 12,
                'mulai' => null,
                'berakhir' => null,
                'created_at' => '2024-09-10 08:10:06',
                'updated_at' => '2024-09-10 08:10:06',
            ],
            [
                'id' => 71,
                'data_karyawan_id' => '5-10',
                'nama' => 'Apriliani Kartika Sari Ali',
                'divisi' => 'Hall Waiters',
                'jumlah_hadir' => 28,
                'mulai' => null,
                'berakhir' => null,
                'created_at' => '2024-09-10 08:10:06',
                'updated_at' => '2024-09-10 08:10:06',
            ],
            [
                'id' => 72,
                'data_karyawan_id' => '5-11',
                'nama' => 'Asriana Fitria Auliana Syam',
                'divisi' => 'Hall Waitress',
                'jumlah_hadir' => 28,
                'mulai' => null,
                'berakhir' => null,
                'created_at' => '2024-09-10 08:10:06',
                'updated_at' => '2024-09-10 08:10:06',
            ],
            [
                'id' => 73,
                'data_karyawan_id' => '5-12',
                'nama' => 'Ayu Meylani',
                'divisi' => 'Hall Waitress',
                'jumlah_hadir' => 4,
                'mulai' => null,
                'berakhir' => null,
                'created_at' => '2024-09-10 08:10:06',
                'updated_at' => '2024-09-10 08:10:06',
            ],
            [
                'id' => 74,
                'data_karyawan_id' => '5-13',
                'nama' => 'Bambang Wiranata',
                'divisi' => 'Cook',
                'jumlah_hadir' => 29,
                'mulai' => null,
                'berakhir' => null,
                'created_at' => '2024-09-10 08:10:06',
                'updated_at' => '2024-09-10 08:10:06',
            ],
            [
                'id' => 75,
                'data_karyawan_id' => '5-14',
                'nama' => 'Erawasi',
                'divisi' => 'Hall Waiters',
                'jumlah_hadir' => 4,
                'mulai' => null,
                'berakhir' => null,
                'created_at' => '2024-09-10 08:10:06',
                'updated_at' => '2024-09-10 08:10:06',
            ],
            [
                'id' => 76,
                'data_karyawan_id' => '5-15',
                'nama' => 'Fadli. M',
                'divisi' => 'Runner',
                'jumlah_hadir' => 5,
                'mulai' => null,
                'berakhir' => null,
                'created_at' => '2024-09-10 08:10:06',
                'updated_at' => '2024-09-10 08:10:06',
            ],
            [
                'id' => 77,
                'data_karyawan_id' => '5-16',
                'nama' => 'Fatchurrahman',
                'divisi' => 'Runner',
                'jumlah_hadir' => 5,
                'mulai' => null,
                'berakhir' => null,
                'created_at' => '2024-09-10 08:10:06',
                'updated_at' => '2024-09-10 08:10:06',
            ],
            [
                'id' => 78,
                'data_karyawan_id' => '5-17',
                'nama' => 'Gika Purnama Putra',
                'divisi' => 'Kitchen Cook',
                'jumlah_hadir' => 6,
                'mulai' => null,
                'berakhir' => null,
                'created_at' => '2024-09-10 08:10:06',
                'updated_at' => '2024-09-10 08:10:06',
            ],
            [
                'id' => 79,
                'data_karyawan_id' => '5-18',
                'nama' => 'Gilang',
                'divisi' => 'Hall Cleaning Service',
                'jumlah_hadir' => 7,
                'mulai' => null,
                'berakhir' => null,
                'created_at' => '2024-09-10 08:10:06',
                'updated_at' => '2024-09-10 08:10:06',
            ],
            [
                'id' => 80,
                'data_karyawan_id' => '5-19',
                'nama' => 'Gilang Alexander Durandt',
                'divisi' => 'Kitchen Helper',
                'jumlah_hadir' => 7,
                'mulai' => null,
                'berakhir' => null,
                'created_at' => '2024-09-10 08:10:06',
                'updated_at' => '2024-09-10 08:10:06',
            ],
            [
                'id' => 81,
                'data_karyawan_id' => '5-20',
                'nama' => 'Hamdana',
                'divisi' => 'Bartender',
                'jumlah_hadir' => 18,
                'mulai' => null,
                'berakhir' => null,
                'created_at' => '2024-09-10 08:10:06',
                'updated_at' => '2024-09-10 08:10:06',
            ],
            [
                'id' => 82,
                'data_karyawan_id' => '5-21',
                'nama' => 'Hasni Arrahma Rahman',
                'divisi' => 'Hall Waiters',
                'jumlah_hadir' => 15,
                'mulai' => null,
                'berakhir' => null,
                'created_at' => '2024-09-10 08:10:06',
                'updated_at' => '2024-09-10 08:10:06',
            ],
            [
                'id' => 83,
                'data_karyawan_id' => '5-22',
                'nama' => 'Ilyan Ashari',
                'divisi' => 'Waiter',
                'jumlah_hadir' => 25,
                'mulai' => null,
                'berakhir' => null,
                'created_at' => '2024-09-10 08:10:06',
                'updated_at' => '2024-09-10 08:10:06',
            ],
            [
                'id' => 84,
                'data_karyawan_id' => '5-23',
                'nama' => 'Irfandi',
                'divisi' => 'Hall Cleaning Service',
                'jumlah_hadir' => 24,
                'mulai' => null,
                'berakhir' => null,
                'created_at' => '2024-09-10 08:10:06',
                'updated_at' => '2024-09-10 08:10:06',
            ],
            [
                'id' => 85,
                'data_karyawan_id' => '5-24',
                'nama' => 'Ishaq',
                'divisi' => 'Pengawas Lapangan',
                'jumlah_hadir' => 26,
                'mulai' => null,
                'berakhir' => null,
                'created_at' => '2024-09-10 08:10:06',
                'updated_at' => '2024-09-10 08:10:06',
            ],
            [
                'id' => 86,
                'data_karyawan_id' => '5-25',
                'nama' => 'Janwar Gunawan',
                'divisi' => 'Hall Cleaning Service',
                'jumlah_hadir' => 24,
                'mulai' => null,
                'berakhir' => null,
                'created_at' => '2024-09-10 08:10:06',
                'updated_at' => '2024-09-10 08:10:06',
            ],
            [
                'id' => 87,
                'data_karyawan_id' => '5-26',
                'nama' => 'Kirani Takhfa Rusyda',
                'divisi' => 'Hall Waiters',
                'jumlah_hadir' => 28,
                'mulai' => null,
                'berakhir' => null,
                'created_at' => '2024-09-10 08:10:06',
                'updated_at' => '2024-09-10 08:10:06',
            ],
            [
                'id' => 88,
                'data_karyawan_id' => '5-27',
                'nama' => 'Lisa',
                'divisi' => 'Accounting',
                'jumlah_hadir' => 29,
                'mulai' => null,
                'berakhir' => null,
                'created_at' => '2024-09-10 08:10:06',
                'updated_at' => '2024-09-10 08:10:06',
            ],
            [
                'id' => 89,
                'data_karyawan_id' => '5-28',
                'nama' => 'M. Alif Akbar',
                'divisi' => 'Runner',
                'jumlah_hadir' => 4,
                'mulai' => null,
                'berakhir' => null,
                'created_at' => '2024-09-10 08:10:06',
                'updated_at' => '2024-09-10 08:10:06',
            ],
            [
                'id' => 90,
                'data_karyawan_id' => '5-29',
                'nama' => 'M Fajar Bahari',
                'divisi' => 'Cook',
                'jumlah_hadir' => 28,
                'mulai' => null,
                'berakhir' => null,
                'created_at' => '2024-09-10 08:10:06',
                'updated_at' => '2024-09-10 08:10:06',
            ],
            [
                'id' => 91,
                'data_karyawan_id' => '5-30',
                'nama' => 'Maharani Afifa',
                'divisi' => 'Hall Cashier',
                'jumlah_hadir' => 21,
                'mulai' => null,
                'berakhir' => null,
                'created_at' => '2024-09-10 08:10:06',
                'updated_at' => '2024-09-10 08:10:06',
            ],
            [
                'id' => 92,
                'data_karyawan_id' => '5-31',
                'nama' => 'Mecarania Hidayat',
                'divisi' => 'Hall Waiters',
                'jumlah_hadir' => 21,
                'mulai' => null,
                'berakhir' => null,
                'created_at' => '2024-09-10 08:10:06',
                'updated_at' => '2024-09-10 08:10:06',
            ],
            [
                'id' => 93,
                'data_karyawan_id' => '5-32',
                'nama' => 'Megawati',
                'divisi' => 'Runner',
                'jumlah_hadir' => 4,
                'mulai' => null,
                'berakhir' => null,
                'created_at' => '2024-09-10 08:10:06',
                'updated_at' => '2024-09-10 08:10:06',
            ],
            [
                'id' => 94,
                'data_karyawan_id' => '5-33',
                'nama' => 'Moh. Rifaah Mahfudz',
                'divisi' => 'Helper',
                'jumlah_hadir' => 27,
                'mulai' => null,
                'berakhir' => null,
                'created_at' => '2024-09-10 08:10:06',
                'updated_at' => '2024-09-10 08:10:06',
            ],
            [
                'id' => 95,
                'data_karyawan_id' => '5-34',
                'nama' => 'Muh Ali Akbar',
                'divisi' => 'Hall Cleaning Service',
                'jumlah_hadir' => 24,
                'mulai' => null,
                'berakhir' => null,
                'created_at' => '2024-09-10 08:10:06',
                'updated_at' => '2024-09-10 08:10:06',
            ],
            [
                'id' => 96,
                'data_karyawan_id' => '5-35',
                'nama' => 'Muh Farhan',
                'divisi' => 'Hall Waiters',
                'jumlah_hadir' => 10,
                'mulai' => null,
                'berakhir' => null,
                'created_at' => '2024-09-10 08:10:06',
                'updated_at' => '2024-09-10 08:10:06',
            ],
            [
                'id' => 97,
                'data_karyawan_id' => '5-36',
                'nama' => 'Muh Fitra Ramadhan',
                'divisi' => 'Pembakaran',
                'jumlah_hadir' => 28,
                'mulai' => null,
                'berakhir' => null,
                'created_at' => '2024-09-10 08:10:06',
                'updated_at' => '2024-09-10 08:10:06',
            ],
            [
                'id' => 98,
                'data_karyawan_id' => '5-37',
                'nama' => 'Muh. Ilham',
                'divisi' => 'Frying',
                'jumlah_hadir' => 28,
                'mulai' => null,
                'berakhir' => null,
                'created_at' => '2024-09-10 08:10:06',
                'updated_at' => '2024-09-10 08:10:06',
            ],
            [
                'id' => 99,
                'data_karyawan_id' => '5-38',
                'nama' => 'Muh Rafly Ahmad',
                'divisi' => 'Kitchen Helper',
                'jumlah_hadir' => 29,
                'mulai' => null,
                'berakhir' => null,
                'created_at' => '2024-09-10 08:10:06',
                'updated_at' => '2024-09-10 08:10:06',
            ],
            [
                'id' => 100,
                'data_karyawan_id' => '5-39',
                'nama' => 'Muh Reza',
                'divisi' => 'Runner',
                'jumlah_hadir' => 5,
                'mulai' => null,
                'berakhir' => null,
                'created_at' => '2024-09-10 08:10:06',
                'updated_at' => '2024-09-10 08:10:06',
            ],
            [
                'id' => 101,
                'data_karyawan_id' => '5-40',
                'nama' => 'Muh Rusdi',
                'divisi' => 'Kitchen Cook',
                'jumlah_hadir' => 15,
                'mulai' => null,
                'berakhir' => null,
                'created_at' => '2024-09-10 08:10:06',
                'updated_at' => '2024-09-10 08:10:06',
            ],
            [
                'id' => 102,
                'data_karyawan_id' => '5-41',
                'nama' => 'Muh. Ilyas B',
                'divisi' => 'Frying',
                'jumlah_hadir' => 30,
                'mulai' => null,
                'berakhir' => null,
                'created_at' => '2024-09-10 08:10:06',
                'updated_at' => '2024-09-10 08:10:06',
            ],
            [
                'id' => 103,
                'data_karyawan_id' => '5-42',
                'nama' => 'Muhammad Ali Al Khumais',
                'divisi' => 'Hall Waiters',
                'jumlah_hadir' => 12,
                'mulai' => null,
                'berakhir' => null,
                'created_at' => '2024-09-10 08:10:06',
                'updated_at' => '2024-09-10 08:10:06',
            ],
            [
                'id' => 104,
                'data_karyawan_id' => '5-43',
                'nama' => 'Muhammad Danial Ibrahim',
                'divisi' => 'Hall Waiters',
                'jumlah_hadir' => 5,
                'mulai' => null,
            ],
        ]); 
    }
}
